apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
    artifacts:
      - image: abassadey/customer-service
deploy:
  kubectl:
    manifests:
      - k8s/manifests/deployment.yaml